group=fun.bm.lecithin
mcVersion=26.3
apiVersion=26.3
channel=ALPHA
clipVersion=1.0.4
weightVersion=1.0.2
# true for release, false for skip release, pre for pre-release
release=pre
# true for push to repo, false for skip push repo, auto for detect by release value
pushRepo=auto

lophineRef=e6aa8084e341f2522ae6809ce4dfbda5912a7000

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
