group=fun.bm.lecithin
mcVersion=26.2
apiVersion=26.2
channel=BETA
clipVersion=1.0.3
weightVersion=1.0.1
# true for release, false for skip release, pre for pre-release
release=pre
# true for push to repo, false for skip push repo, auto for detect by release value
pushRepo=auto

lophineRef=9c89226c265931206ddcc952835fb32bb85efcc1

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
