group=fun.bm.lecithin
mcVersion=26.2
apiVersion=26.2
channel=BETA
clipVersion=1.0.1
weightVersion=1.0.0
# true for release, false for skip release, pre for pre-release
release=pre
# true for push to repo, false for skip push repo, auto for detect by release value
pushRepo=auto

lophineRef=bc13a2ab72a1c957fa36436ea0f71a71e8c394c2

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
